[32mINFO    [0m test_sign_in_password:test_E2E.py:24 Testcase: Sign in with Password
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103749b10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10374a750>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10374aad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e4c90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e6090>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034e7390>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b5746c958ffdbb5cca4397e864fa4431